// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cvLMRCpp
double cvLMRCpp(const arma::mat& X, const arma::vec& y, const arma::uword k0, const double lambda, const bool generalized, const int seed, const int nThreads, const double tolerance, const bool center);
RcppExport SEXP _cvLM_cvLMRCpp(SEXP XSEXP, SEXP ySEXP, SEXP k0SEXP, SEXP lambdaSEXP, SEXP generalizedSEXP, SEXP seedSEXP, SEXP nThreadsSEXP, SEXP toleranceSEXP, SEXP centerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type k0(k0SEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const bool >::type generalized(generalizedSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const int >::type nThreads(nThreadsSEXP);
    Rcpp::traits::input_parameter< const double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< const bool >::type center(centerSEXP);
    rcpp_result_gen = Rcpp::wrap(cvLMRCpp(X, y, k0, lambda, generalized, seed, nThreads, tolerance, center));
    return rcpp_result_gen;
END_RCPP
}
// gridSearch
Rcpp::List gridSearch(const arma::mat& X, const arma::vec& y, const int k0, const double maxLambda, const double precision, const bool generalized, const int seed, const int nThreads, const double tolerance, const bool center);
RcppExport SEXP _cvLM_gridSearch(SEXP XSEXP, SEXP ySEXP, SEXP k0SEXP, SEXP maxLambdaSEXP, SEXP precisionSEXP, SEXP generalizedSEXP, SEXP seedSEXP, SEXP nThreadsSEXP, SEXP toleranceSEXP, SEXP centerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const int >::type k0(k0SEXP);
    Rcpp::traits::input_parameter< const double >::type maxLambda(maxLambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type precision(precisionSEXP);
    Rcpp::traits::input_parameter< const bool >::type generalized(generalizedSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const int >::type nThreads(nThreadsSEXP);
    Rcpp::traits::input_parameter< const double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< const bool >::type center(centerSEXP);
    rcpp_result_gen = Rcpp::wrap(gridSearch(X, y, k0, maxLambda, precision, generalized, seed, nThreads, tolerance, center));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cvLM_cvLMRCpp", (DL_FUNC) &_cvLM_cvLMRCpp, 9},
    {"_cvLM_gridSearch", (DL_FUNC) &_cvLM_gridSearch, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_cvLM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
