# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cv.lm.rcpp <- function(y, X, K0, lambda, generalized, seed, nthreads) {
    .Call(`_cvLM_cvLMrcpp`, y, X, K0, lambda, generalized, seed, nthreads)
}

