# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cv.lm.rcpp <- function(y, x, k0, lambda, generalized, seed, nThreads, threshold, center) {
    .Call(`_cvLM_cvLMRCpp`, y, x, k0, lambda, generalized, seed, nThreads, threshold, center)
}

grid.search.rcpp <- function(y, x, k0, maxLambda, precision, generalized, seed, nThreads, threshold, center) {
    .Call(`_cvLM_gridSearch`, y, x, k0, maxLambda, precision, generalized, seed, nThreads, threshold, center)
}

